language: c

compiler: gcc

os:
  # - osx
  - linux

before_install:
  - mkdir -p build
  - cp Example/compress/sample.txt build/sample.txt

branches:
  only:
    - master

jobs:
  include:
    - script: ./run bfs
      name: bfs
    - script: ./run bissearch
      name: bissearch
    - script: ./run bistree
      name: bistree
    - script: ./run bit
      name: bit
    - script: ./run bitree
      name: bitree
    - script: ./run cbc
      name: cbc
    - script: ./run chtbl
      name: chtbl
    - script: ./run clist
      name: clist
    - script: ./run compress
      name: compress
    - script: ./run cover
      name: cover
    - script: ./run dfs
      name: dfs
    - script: ./run directls
      name: directls
    - script: ./run dlist
      name: dlist
    - script: ./run encryption
      name: encryption
    - script: ./run geodist
      name: geodist
    - script: ./run geometry
      name: geometry
    - script: ./run graph
      name: graph
    - script: ./run graphalg
      name: graphalg
    - script: ./run heap
      name: heap
    - script: ./run list
      name: list
    - script: ./run nummeths
      name: nummeths
    - script: ./run ohtbl
      name: ohtbl
    - script: ./run page
      name: page
    - script: ./run pqueue
      name: pqueue
    - script: ./run queue
      name: queue
    - script: ./run routing
      name: routing
    - script: ./run set
      name: set
    - script: ./run sort
      name: sort
    - script: ./run spell
      name: spell
    - script: ./run stack
      name: stack
